name: readit
description: A reddit client.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_collection: ^4.3.0
  built_value: ^7.0.0
  dio: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  built_value_generator: ^7.0.0
  pedantic: ^1.8.0+1
  test: ^1.9.4

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
